import 'package:chopper/chopper.dart';

part 'post_api_service.chopper.dart';
/**
 * Created by cett01 on 20.07.2020
 */

///Run this comment on terminal for autogenerated file
///```
///flutter packages pub run build_runner watch
///```

@ChopperApi(baseUrl: "<apiurl>")
abstract class PostApiService extends ChopperService {
  @Post(path: "/user/login")
  Future<Response> userLogin(
      @Field("username") String username, @Field("password") String password);

  @Post(path: "/user/register")
  Future<Response> userRegister(
      @Field("email") String mail,
      @Field("name") String nameSurname,
      @Field("pno") int phoneNumber,
      @Field("gender") String gender,
      @Field("password") String password,
      @Field("uuid") String uniqueId,
      @Field("registration_token") String registrationToken);

  @Post(path: "/user/logout")
  Future<Response> logout(@Header("token") String token);

  @Get(path: "/book/denemecreate")
  Future<Response> createDeneme(
      @Header("token") String token, @Query("level") int level);

  static PostApiService create() {
    final client = ChopperClient(
        baseUrl: "apiurl",
        services: [
          _$PostApiService(),
        ],
        converter: JsonConverter());
    return _$PostApiService(client);
  }
}
